# Generated by Django 4.1.2 on 2022-10-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracksmusicarea',
            options={'verbose_name': 'Мои треки', 'verbose_name_plural': 'Мои треки'},
        ),
        migrations.AlterField(
            model_name='tracksmusicarea',
            name='tracks_date_added',
            field=models.DateField(verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='tracksmusicarea',
            name='tracks_images',
            field=models.ImageField(upload_to='tracks_images/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='tracksmusicarea',
            name='tracks_music',
            field=models.FileField(upload_to='tracks_music/', verbose_name='Загрузка трека'),
        ),
        migrations.AlterField(
            model_name='tracksmusicarea',
            name='tracks_title',
            field=models.CharField(max_length=150, verbose_name='Название трека'),
        ),
    ]
