# Generated by Django 4.1.2 on 2022-10-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_title', models.CharField(max_length=250, verbose_name='Место')),
                ('place_description', models.CharField(max_length=250, verbose_name='Описание места')),
                ('number', models.CharField(max_length=250, verbose_name='Телефон')),
                ('working_hours', models.CharField(max_length=250, verbose_name='Часы работы')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('email_description', models.CharField(max_length=250, verbose_name='Описание Email')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Место',
            },
        ),
    ]
