# Generated by Django 4.1.2 on 2022-10-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='')),
                ('name', models.CharField(max_length=250, verbose_name='')),
                ('get_in_touch_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='')),
            ],
            options={
                'verbose_name': 'Связаться',
                'verbose_name_plural': 'Связаться',
            },
        ),
    ]
