# Generated by Django 4.1.2 on 2022-10-25 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_images', models.ImageField(upload_to='author_images/', verbose_name='Фото')),
                ('author_title', models.CharField(max_length=150, verbose_name='Имя')),
                ('author_descriptions', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автор',
            },
        ),
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('blog_images', models.ImageField(upload_to='blog_images/', verbose_name='Фото')),
                ('blog_title', models.CharField(max_length=150, unique=True, verbose_name='Заголовок')),
                ('blog_descriptions', models.TextField(verbose_name='Описание')),
                ('blog_who_posted', models.CharField(max_length=150, verbose_name='Кто опубликовал пост')),
                ('blog_comments', models.CharField(max_length=150, verbose_name='Коментарии')),
                ('blog_date_added', models.DateField(verbose_name='Дата добавления')),
                ('blog_cards', models.TextField(null=True, verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.CreateModel(
            name='InstagramFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_images', models.ImageField(upload_to='instagram_feeds/', verbose_name='Фото из Инсты')),
            ],
            options={
                'verbose_name': 'Instagram',
                'verbose_name_plural': 'Instagram',
            },
        ),
        migrations.CreateModel(
            name='RecentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('recent_date_added', models.DateField(verbose_name='Дата добавления')),
                ('recent_images', models.ImageField(upload_to='recent_post/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Недавний посты',
                'verbose_name_plural': 'Недавние посты',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('categories_name', models.CharField(max_length=255, verbose_name='Категория')),
                ('categories_number', models.ManyToManyField(blank=True, default=None, related_name='number_cat', to='blog.blogscategories')),
            ],
            options={
                'verbose_name': 'Категория Блога',
                'verbose_name_plural': 'Категории Блога',
            },
        ),
        migrations.AddField(
            model_name='blogposts',
            name='blog_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.blogscategories', verbose_name='Категория поста'),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
