# Generated by Django 4.1.2 on 2022-10-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_images', models.ImageField(upload_to='blog_images/', verbose_name='')),
                ('blog_title', models.CharField(max_length=150, verbose_name='')),
                ('blog_descriptions', models.TextField(verbose_name='')),
                ('blog_who_posted', models.TextField(max_length=150, verbose_name='')),
                ('blog_comments', models.CharField(max_length=150, verbose_name='')),
                ('blog_date_added', models.DateField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.CreateModel(
            name='BlogsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_name', models.CharField(max_length=255, verbose_name='')),
            ],
            options={
                'verbose_name': 'Категория Блога',
                'verbose_name_plural': 'Категории Блога',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images_comments/')),
                ('name', models.CharField(max_length=150, verbose_name='')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='blog.blogposts')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='blogposts',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.blogscategories', verbose_name=''),
        ),
    ]
