# Generated by Django 4.1.2 on 2022-10-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('details_descriptions', models.TextField(verbose_name='Описание')),
                ('details_card', models.TextField(verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.blogscategories', verbose_name='Категория поста'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='blog_comments',
            field=models.CharField(max_length=150, verbose_name='Коментарии'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='blog_date_added',
            field=models.DateField(verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='blog_descriptions',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='blog_images',
            field=models.ImageField(upload_to='blog_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='blog_title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='blog_who_posted',
            field=models.CharField(max_length=150, verbose_name='Кто опубликовал пост'),
        ),
    ]
