# Generated by Django 4.1.2 on 2022-10-22 20:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_detailsblog_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_title', models.CharField(max_length=250, verbose_name='')),
                ('recent_date_added', models.DateField(verbose_name='')),
                ('recent_images', models.ImageField(upload_to='recent_post/', verbose_name='')),
            ],
            options={
                'verbose_name': 'Недавний посты',
                'verbose_name_plural': 'Недавние посты',
            },
        ),
        migrations.AlterField(
            model_name='detailsblog',
            name='details_descriptions',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
