# Generated by Django 4.1.2 on 2022-10-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recentpost_alter_detailsblog_details_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_images', models.ImageField(upload_to='instagram_feeds/', verbose_name='Фото из Инсты')),
            ],
            options={
                'verbose_name': 'Instagram',
                'verbose_name_plural': 'Instagram',
            },
        ),
        migrations.AlterField(
            model_name='recentpost',
            name='recent_date_added',
            field=models.DateField(verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='recentpost',
            name='recent_images',
            field=models.ImageField(upload_to='recent_post/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='recentpost',
            name='recent_title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
    ]
