# Generated by Django 4.1.2 on 2022-10-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogposts_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='blog_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amount', to='blog.blogscategories', verbose_name='Категория поста'),
        ),
    ]
