# Generated by Django 4.1.2 on 2022-10-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogposts_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_images', models.ImageField(upload_to='author_images/', verbose_name='Фото')),
                ('author_title', models.CharField(max_length=150, verbose_name='Имя')),
                ('author_descriptions', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автор',
            },
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='blog_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.blogscategories', verbose_name='Категория поста'),
        ),
    ]
