# Generated by Django 4.1.2 on 2022-10-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_authorblog_alter_blogposts_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogscategories',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
