# Generated by Django 4.1.2 on 2022-10-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogscategories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='blogscategories',
            name='categories_name',
            field=models.CharField(max_length=255, verbose_name='Категория'),
        ),
    ]
