# Generated by Django 4.1.2 on 2022-10-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogposts_slug_alter_blogscategories_categories_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='slug',
        ),
    ]
