# Generated by Django 4.1.2 on 2022-10-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blogposts_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogscategories',
            name='slug',
        ),
        migrations.AddField(
            model_name='detailsblog',
            name='details_blog_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.blogposts', verbose_name='На пост'),
        ),
    ]
