# Generated by Django 4.1.2 on 2022-10-24 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_blogposts_likes_blogposts_slug_blogscategories_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='slug',
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
