# Generated by Django 4.1.2 on 2022-10-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blogposts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
