# Generated by Django 4.1.2 on 2022-10-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogscategories_categories_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='blogscategories',
            name='categories_count',
        ),
        migrations.AddField(
            model_name='blogscategories',
            name='categories_number',
            field=models.ManyToManyField(blank=True, default=None, related_name='number_cat', to='blog.blogscategories'),
        ),
    ]
