# Generated by Django 4.1.2 on 2022-10-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_commentpost_delete_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentpost',
            name='img',
            field=models.ImageField(null=True, upload_to='comment_post/'),
        ),
    ]
