# Generated by Django 4.1.2 on 2022-10-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_commentpost_created_commentpost_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='img',
        ),
        migrations.AddField(
            model_name='commentpost',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
