# Generated by Django 4.1.2 on 2022-10-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('title', models.CharField(max_length=255, verbose_name='Заголово')),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
