# Generated by Django 4.1.2 on 2022-10-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_galleriesmodel_alter_imagemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_title', models.CharField(max_length=150, verbose_name='')),
                ('audio_images', models.ImageField(upload_to='images_audio_area/', verbose_name='')),
                ('audio_date_added', models.DateField()),
                ('audio_file', models.FileField(upload_to='file_audio_area/')),
            ],
            options={
                'verbose_name': 'Аудио зона',
                'verbose_name_plural': 'Аудио зоны',
            },
        ),
    ]
