# Generated by Django 4.1.2 on 2022-10-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutarea',
            name='area_painting',
            field=models.ImageField(null=True, upload_to='area_images/', verbose_name='Роспись'),
        ),
    ]
