# Generated by Django 4.1.2 on 2022-10-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutvideo',
            name='about_images',
            field=models.ImageField(null=True, upload_to='about_images/', verbose_name='Превью'),
        ),
    ]
