# Generated by Django 4.1.2 on 2022-10-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutvideo_about_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutvideo',
            name='about_video',
            field=models.CharField(max_length=250, verbose_name='URL на видео в Ютубе'),
        ),
    ]
